version: "3.9"

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app  # Optional, for local development to reflect changes in real-time