"""initial

Revision ID: 122fd4b793bd
Revises: 
Create Date: 2026-06-09 14:37:23.793599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122fd4b793bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('pais', sa.String(length=10), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.String(length=20), nullable=True),
    sa.Column('tipo_negocio', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_ferias_ano',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('dias', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('contacto', sa.String(length=20), nullable=True),
    sa.Column('num_maquinas', sa.Integer(), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('data_instalacao', sa.String(length=20), nullable=True),
    sa.Column('proxima_manutencao', sa.String(length=20), nullable=True),
    sa.Column('tipo_servico', sa.String(length=100), nullable=True),
    sa.Column('morada', sa.String(length=300), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('valor_pago', sa.Float(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('nome_completo', sa.String(length=200), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizacao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('faturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('local', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data', sa.String(length=20), nullable=False),
    sa.Column('nota', sa.String(length=500), nullable=True),
    sa.Column('ficheiro', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.String(length=20), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizacao.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ferias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.String(length=20), nullable=False),
    sa.Column('data_fim', sa.String(length=20), nullable=False),
    sa.Column('nota', sa.String(length=300), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('comentario_admin', sa.String(length=300), nullable=True),
    sa.Column('aprovado_por', sa.String(length=100), nullable=True),
    sa.Column('num_dias', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=20), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizacao.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horastrabalhadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_nome', sa.String(length=100), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Integer(), nullable=False),
    sa.Column('manha', sa.Float(), nullable=True),
    sa.Column('tarde', sa.Float(), nullable=True),
    sa.Column('extra', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.String(length=300), nullable=True),
    sa.Column('local', sa.String(length=200), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizacao.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('destinatario', sa.String(length=50), nullable=False),
    sa.Column('contacto', sa.String(length=20), nullable=False),
    sa.Column('mensagem', sa.String(length=1000), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizacao.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('criada_em', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('local', sa.String(length=300), nullable=True),
    sa.Column('data_inicio', sa.String(length=20), nullable=False),
    sa.Column('data_fim', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orcamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=200), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('num_maquinas', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=20), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizacao.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizacao.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registo_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('tipo_servico', sa.String(length=100), nullable=True),
    sa.Column('data_servico', sa.String(length=20), nullable=True),
    sa.Column('proxima_manutencao', sa.String(length=20), nullable=True),
    sa.Column('num_maquinas', sa.Integer(), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('valor_pago', sa.Float(), nullable=True),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('duracao_horas', sa.Float(), nullable=True),
    sa.Column('created_at', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizacao.id'], ),
    sa.ForeignKeyConstraint(['registo_id'], ['registos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obra_funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizacao.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('obra_funcionario')
    op.drop_table('servicos')
    op.drop_table('push_subscriptions')
    op.drop_table('orcamentos')
    op.drop_table('obras')
    op.drop_table('notificacoes')
    op.drop_table('mensagens')
    op.drop_table('horastrabalhadas')
    op.drop_table('ferias')
    op.drop_table('faturas')
    op.drop_table('usuario')
    op.drop_table('tipos_servico')
    op.drop_table('registos')
    op.drop_table('config_ferias_ano')
    op.drop_table('organizacao')
    # ### end Alembic commands ###
